/* MOTOR_A_DIR_L PB0 */
#define DDR_MOTOR_A_DIR_L DDRB
#define PORT_MOTOR_A_DIR_L PORTB
#define BIT_MOTOR_A_DIR_L PB0
/* MOTOR_A_DIR_R PB1 */
#define DDR_MOTOR_A_DIR_R DDRB
#define PORT_MOTOR_A_DIR_R PORTB
#define BIT_MOTOR_A_DIR_R PB1

/* SW_A_ZERO PB4 */
#define DDR_SW_A_ZERO DDRB
#define PORT_SW_A_ZERO PORTB
#define PIN_SW_A_ZERO PINB
#define BIT_SW_A_ZERO PB4
/* SW_A_END PD2 */
#define DDR_SW_A_END DDRD
#define PORT_SW_A_END PORTD
#define PIN_SW_A_END PIND
#define BIT_SW_A_END PD2

/* MOTOR_B_DIR_L PD0 */
#define DDR_MOTOR_B_DIR_L DDRD
#define PORT_MOTOR_B_DIR_L PORTD
#define BIT_MOTOR_B_DIR_L PD0
/* MOTOR_B_DIR_R PD1 */
#define DDR_MOTOR_B_DIR_R DDRD
#define PORT_MOTOR_B_DIR_R PORTD
#define BIT_MOTOR_B_DIR_R PD1

/* SW_B_ZERO PB3 */
#define DDR_SW_B_ZERO DDRB
#define PORT_SW_B_ZERO PORTB
#define PIN_SW_B_ZERO PINB
#define BIT_SW_B_ZERO PB3
/* SW_B_END PD3 */
#define DDR_SW_B_END DDRD
#define PORT_SW_B_END PORTD
#define PIN_SW_B_END PIND
#define BIT_SW_B_END PD3

/* TWI_ADDR_BIT_1 PD6 */
#define DDR_TWI_ADDR_BIT_1 DDRD
#define PIN_TWI_ADDR_BIT_1 PIND
#define PORT_TWI_ADDR_BIT_1 PORTD
#define BIT_TWI_ADDR_BIT_1 PD6
